Traceback (most recent call last):
  File "/home/joyrose-kinuthia/development/code/phase4/uni-cart/server/app.py", line 14, in <module>
    db.init_app(app)
  File "/home/joyrose-kinuthia/development/code/phase4/uni-cart/venv/lib/python3.12/site-packages/flask_sqlalchemy/extension.py", line 312, in init_app
    raise RuntimeError(
RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.
